version: "3"
services:
  app:
    build: .
    volumes:
      - ./app/:/home/app/
    depends_on:
      - db
    links:
      - db:db
    networks:
      - ship_cars_network
  db:
    restart: always
    image: postgres:10
    env_file: .env
    expose:
      - 5432
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - ship_cars_network

volumes:
  db:

networks:
  ship_cars_network:
     driver: bridge